controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forklift_controller:
      type: position_controllers/JointGroupPositionController

forklift_controller:
  ros__parameters:
    joints:
      - inner_mast_joint
      - fork_carriage_joint
    command_interfaces: 
      - position 
    state_interfaces: 
      - position 
      - velocity 